### ISSUE TITLE
Fonctionnement du Script VBS

### ISSUE THREAD

**Issue by jpose** [PluginsOCSInventory-NG/winupdate#2]
Bonjour,

Après une installation sur serveur OCS 2.2.1 via le menu de gestion des plugins.Le script fonctionne correctement en local mais le xml généré ne contient aucunes informations les balises restent vides.

```
    <WINUPDATESTATE>
        <AUOPTIONS />
        <SCHEDULEDINSTALLDATE />
        <LASTSUCCESSTIME />
        <DETECTSUCCESSTIME />
        <DOWNLOADSUCCESSTIME />
    </WINUPDATESTATE>
```

Le mode debug ne m'avance pas puisque pour lui le script s'exécute correctement :(

EXECUTABLE PLUGIN => Plugin <winupdate.vbs> executed successfully

Merci :)

**Comment by vdeville** [comment]
Bonsoir @jpose et merci de votre retour,
Pourriez-vous nous communiquer les informations de la machine concernée ?
Quel version de Windows ainsi que la version de l'Agent OCS ?
Quand vous exécutez le VBS à la main le retour est-il également vide ?
Dans l'attente d'une réponse de votre part

**Comment by jpose** [comment]
Bonjour,

Il s'agit de postes Lenovo M73, en Windows 7 x64 Pro avec OCS Inventory NG Agent 2.1.1.3. Le VBS fonctionne "à la main" mais lorsque l'agent l'exécute les champs du xml sont vides. Merci :)

**Comment by vdeville** [comment]
Bonjour @jpose et merci de votre réponse,
Je constate en effet le même soucis de mon côté le VBS ne retourne aucune information concernant les mises à jour. Tester sur un Windows 7 et 10. Nous avont pris en note le problème et le traiteront au plus vite.
Merci de votre retour et bonne journée.

**Comment by Atond** [comment]
Bonjour, des nouvelles pour le fonctionnement sur W7 et W10 ?

**Comment by steph78630** [comment]
Bonjour,

le script fonctionne sur un OS x86 (testé sur XP et W7 32 bits) et affiche correctement les résultats dans la console OCS, mais pas avec l'architecture amd64 ni avec Windows 10.

Comme constaté par @jpose, le script fonctionne en l'exécutant manuellement mais pas via l'agent OCS (balises du fichier XML mal formatées comme détaillé par jpose dans son post initial).

Edit du 22/07/2017 : 

J'ai mis à jour le VBS avec la compatibilité amd64 (toutes versions) ainsi que pour Windows 10 > En attente de validation sur GitHub

**Comment by vdeville** [comment]
Bonjour à tous,
Pourriez-vous réessayer depuis les modifications de @steph78630 ?

Merci

**Comment by gillesdubois** [comment]
Les modifications de @steph78630 ont été intégré au trunk.
Une release sera bientot disponible.
Les tests ont été effectuées sous WIN 7 et WIN 10 et le plugin est fonctionnel.
